# https://taskfile.dev
version: '3'
includes:
  omz: profiles/omz/Taskfile.yml
  ant: profiles/ant/Taskfile.yml
tasks:
  default: Happy with dsh!
  bench: time zsh -lic "exit"
  
  setup: |
    task rc.ln
    
    mkdir -p _local
    ln -sf ~/.tools _local

  rc: ls -ld ~/.z*
  rc.ln: |
    ln -sf {{.TASKFILE_DIR}}/main.zsh ~/.zshrc
    ln -sf {{.TASKFILE_DIR}} ~/.zsh
  rc.rm: rm ~/.zshrc
  