# https://taskfile.dev
version: '3'
includes:
  omz: profiles/omz/Taskfile.yml
  ant: profiles/ant/Taskfile.yml
tasks:
  default: Happy with dsh!
  
  bench: |
    # time zsh -lic "exit"
    # time ( zsh -il -c "exit" ) # test in isolation subshell process
    # hyperfine --ignore-failure 'zsh -lic "exit"'

    # 启动一个带 zprof 监控的 zsh 交互 shell
    zsh -i -l -c '
      # 加载性能分析模块
      zmodload zsh/zprof

      source ~/.zshrc
      # 清屏让输出更好看
      clear

      # 显示分析结果
      # 第1列是调用次数，第2列是总耗时(ms)，第3列是平均耗时
      zprof | head -n 20

      exit
    '

  doc: |
    mkdir -p doc
    cd doc

    man zshbuiltins | col -b > zshbuiltins.txt
  
  ## Setup

  setup: |
    task rc.ln
    
    mkdir -p _local
    ln -sf ~/.tools _local

  rc: ls -ld ~/.z*
  rc.ln: |
    # todo better refactor
    [ -f ~/.zshrc ] && {
      bakfile=~/.zshrc.bak-$(date '+%Y-%m-%dT%H-%M-%S')
      mv ~/.zshrc $bakfile
      echo "backup into $bakfile"
    }
    ln -sf {{.TASKFILE_DIR}}/main.zsh ~/.zshrc
    ln -sf {{.TASKFILE_DIR}} ~/.zsh
  rc.rm: rm ~/.zshrc
  